import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/word_question.dart';

class WordQuestionsService {
  static final _supabase = Supabase.instance.client;

  // Fallback hardcoded data (for offline mode or while migrating)
  static final Map<int, List<WordQuestion>> levelQuestions = {
    1: [
      WordQuestion(
        id: 1,
        levelNumber: 1,
        word: 'PORK',
        question: 'Thịt từ lợn',
        hint: 'Pork meat - meat from a pig',
        startRow: 0,
        startCol: 5,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 2,
        levelNumber: 1,
        word: 'BEEF',
        question: 'Thịt từ bò',
        hint: 'Beef - meat from a cow',
        startRow: 1,
        startCol: 1,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 3,
        levelNumber: 1,
        word: 'WATER',
        question: 'Nước uống',
        hint: 'Water - essential liquid for life',
        startRow: 2,
        startCol: 0,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 4,
        levelNumber: 1,
        word: 'NOODLES',
        question: 'Mì ăn liền',
        hint: 'Noodles - popular Asian food',
        startRow: 2,
        startCol: 4,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 5,
        levelNumber: 1,
        word: 'LEMONADE',
        question: 'Nước chanh',
        hint: 'Lemonade - sweet lemon drink',
        startRow: 4,
        startCol: 0,
        direction: 'across',
        number: 5,
      ),
      WordQuestion(
        id: 6,
        levelNumber: 1,
        word: 'CHICKEN',
        question: 'Thịt gà',
        hint: 'Chicken - meat from poultry',
        startRow: 6,
        startCol: 2,
        direction: 'across',
        number: 6,
      ),
    ],
    2: [
      WordQuestion(
        id: 7,
        levelNumber: 2,
        word: 'APPLE',
        question: 'Quả táo',
        hint: 'Apple - red or green fruit',
        startRow: 0,
        startCol: 2,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 8,
        levelNumber: 2,
        word: 'ORANGE',
        question: 'Quả cam',
        hint: 'Orange - citrus fruit with orange color',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 9,
        levelNumber: 2,
        word: 'BANANA',
        question: 'Quả chuối',
        hint: 'Banana - yellow tropical fruit',
        startRow: 2,
        startCol: 5,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 10,
        levelNumber: 2,
        word: 'GRAPE',
        question: 'Quả nho',
        hint: 'Grape - small round fruit',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 11,
        levelNumber: 2,
        word: 'MANGO',
        question: 'Quả xoài',
        hint: 'Mango - king of fruits',
        startRow: 4,
        startCol: 3,
        direction: 'across',
        number: 5,
      ),
    ],
    3: [
      WordQuestion(
        id: 12,
        levelNumber: 3,
        word: 'SHIRT',
        question: 'Áo sơ mi',
        hint: 'Shirt - upper body clothing',
        startRow: 0,
        startCol: 2,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 13,
        levelNumber: 3,
        word: 'PANTS',
        question: 'Quần dài',
        hint: 'Pants - lower body clothing',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 14,
        levelNumber: 3,
        word: 'SHOES',
        question: 'Giày',
        hint: 'Shoes - footwear',
        startRow: 2,
        startCol: 3,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 15,
        levelNumber: 3,
        word: 'COAT',
        question: 'Áo khoác',
        hint: 'Coat - outer wearing garment',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 16,
        levelNumber: 3,
        word: 'HAT',
        question: 'Mũ',
        hint: 'Hat - head covering',
        startRow: 4,
        startCol: 5,
        direction: 'across',
        number: 5,
      ),
    ],
    4: [
      WordQuestion(
        id: 17,
        levelNumber: 4,
        word: 'RED',
        question: 'Màu đỏ',
        hint: 'Red - color of blood',
        startRow: 0,
        startCol: 3,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 18,
        levelNumber: 4,
        word: 'BLUE',
        question: 'Màu xanh lam',
        hint: 'Blue - color of sky',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 19,
        levelNumber: 4,
        word: 'GREEN',
        question: 'Màu xanh lá',
        hint: 'Green - color of grass',
        startRow: 2,
        startCol: 2,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 20,
        levelNumber: 4,
        word: 'YELLOW',
        question: 'Màu vàng',
        hint: 'Yellow - color of sun',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 21,
        levelNumber: 4,
        word: 'BLACK',
        question: 'Màu đen',
        hint: 'Black - darkest color',
        startRow: 4,
        startCol: 4,
        direction: 'across',
        number: 5,
      ),
    ],
    5: [
      WordQuestion(
        id: 22,
        levelNumber: 5,
        word: 'CAT',
        question: 'Con mèo',
        hint: 'Cat - domestic pet animal',
        startRow: 0,
        startCol: 3,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 23,
        levelNumber: 5,
        word: 'DOG',
        question: 'Con chó',
        hint: 'Dog - mans best friend',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 24,
        levelNumber: 5,
        word: 'BIRD',
        question: 'Con chim',
        hint: 'Bird - animal that flies',
        startRow: 2,
        startCol: 2,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 25,
        levelNumber: 5,
        word: 'FISH',
        question: 'Con cá',
        hint: 'Fish - aquatic animal',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 26,
        levelNumber: 5,
        word: 'HORSE',
        question: 'Con ngựa',
        hint: 'Horse - large farm animal',
        startRow: 4,
        startCol: 4,
        direction: 'across',
        number: 5,
      ),
    ],
    6: [
      WordQuestion(
        id: 27,
        levelNumber: 6,
        word: 'STUDENT',
        question: 'Học sinh',
        hint: 'Student - person who studies',
        startRow: 0,
        startCol: 1,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 28,
        levelNumber: 6,
        word: 'TEACHER',
        question: 'Giáo viên',
        hint: 'Teacher - person who teaches',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 29,
        levelNumber: 6,
        word: 'BOOK',
        question: 'Cuốn sách',
        hint: 'Book - object for reading',
        startRow: 2,
        startCol: 3,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 30,
        levelNumber: 6,
        word: 'SCHOOL',
        question: 'Trường học',
        hint: 'School - place of education',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 31,
        levelNumber: 6,
        word: 'PENCIL',
        question: 'Cái bút chì',
        hint: 'Pencil - writing tool',
        startRow: 4,
        startCol: 3,
        direction: 'across',
        number: 5,
      ),
    ],
    7: [
      WordQuestion(
        id: 32,
        levelNumber: 7,
        word: 'MONDAY',
        question: 'Thứ hai',
        hint: 'Monday - first day of work week',
        startRow: 0,
        startCol: 0,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 33,
        levelNumber: 7,
        word: 'TUESDAY',
        question: 'Thứ ba',
        hint: 'Tuesday - second day of week',
        startRow: 1,
        startCol: 2,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 34,
        levelNumber: 7,
        word: 'WEDNESDAY',
        question: 'Thứ tư',
        hint: 'Wednesday - middle of week',
        startRow: 2,
        startCol: 0,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 35,
        levelNumber: 7,
        word: 'FRIDAY',
        question: 'Thứ sáu',
        hint: 'Friday - day before weekend',
        startRow: 3,
        startCol: 3,
        direction: 'across',
        number: 4,
      ),
      WordQuestion(
        id: 36,
        levelNumber: 7,
        word: 'SUNDAY',
        question: 'Chủ nhật',
        hint: 'Sunday - last day of week',
        startRow: 4,
        startCol: 1,
        direction: 'across',
        number: 5,
      ),
    ],
    8: [
      WordQuestion(
        id: 37,
        levelNumber: 8,
        word: 'MORNING',
        question: 'Buổi sáng',
        hint: 'Morning - early part of day',
        startRow: 0,
        startCol: 1,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 38,
        levelNumber: 8,
        word: 'AFTERNOON',
        question: 'Buổi chiều',
        hint: 'Afternoon - middle part of day',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 39,
        levelNumber: 8,
        word: 'EVENING',
        question: 'Buổi tối',
        hint: 'Evening - end of day',
        startRow: 2,
        startCol: 2,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 40,
        levelNumber: 8,
        word: 'NIGHT',
        question: 'Ban đêm',
        hint: 'Night - dark part of day',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 41,
        levelNumber: 8,
        word: 'SLEEP',
        question: 'Ngủ',
        hint: 'Sleep - rest at night',
        startRow: 4,
        startCol: 4,
        direction: 'across',
        number: 5,
      ),
    ],
    9: [
      WordQuestion(
        id: 42,
        levelNumber: 9,
        word: 'FATHER',
        question: 'Cha',
        hint: 'Father - male parent',
        startRow: 0,
        startCol: 1,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 43,
        levelNumber: 9,
        word: 'MOTHER',
        question: 'Mẹ',
        hint: 'Mother - female parent',
        startRow: 1,
        startCol: 0,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 44,
        levelNumber: 9,
        word: 'SISTER',
        question: 'Chị em gái',
        hint: 'Sister - female sibling',
        startRow: 2,
        startCol: 2,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 45,
        levelNumber: 9,
        word: 'BROTHER',
        question: 'Anh em trai',
        hint: 'Brother - male sibling',
        startRow: 2,
        startCol: 0,
        direction: 'down',
        number: 4,
      ),
      WordQuestion(
        id: 46,
        levelNumber: 9,
        word: 'FAMILY',
        question: 'Gia đình',
        hint: 'Family - parents and siblings',
        startRow: 4,
        startCol: 3,
        direction: 'across',
        number: 5,
      ),
    ],
    10: [
      WordQuestion(
        id: 47,
        levelNumber: 10,
        word: 'BREAKFAST',
        question: 'Bữa sáng',
        hint: 'Breakfast - first meal of day',
        startRow: 0,
        startCol: 0,
        direction: 'across',
        number: 1,
      ),
      WordQuestion(
        id: 48,
        levelNumber: 10,
        word: 'LUNCH',
        question: 'Bữa trưa',
        hint: 'Lunch - midday meal',
        startRow: 1,
        startCol: 3,
        direction: 'across',
        number: 2,
      ),
      WordQuestion(
        id: 49,
        levelNumber: 10,
        word: 'DINNER',
        question: 'Bữa tối',
        hint: 'Dinner - evening meal',
        startRow: 2,
        startCol: 1,
        direction: 'across',
        number: 3,
      ),
      WordQuestion(
        id: 50,
        levelNumber: 10,
        word: 'SNACK',
        question: 'Bữa ăn nhẹ',
        hint: 'Snack - light food between meals',
        startRow: 3,
        startCol: 0,
        direction: 'across',
        number: 4,
      ),
      WordQuestion(
        id: 51,
        levelNumber: 10,
        word: 'DRINK',
        question: 'Đồ uống',
        hint: 'Drink - liquid beverage',
        startRow: 4,
        startCol: 2,
        direction: 'across',
        number: 5,
      ),
    ],
  };

  // Get questions for a specific level from Supabase
  static Future<List<WordQuestion>> getQuestionsForLevel(int levelNumber) async {
    try {
      final response = await _supabase
          .from('word_puzzle_questions')
          .select()
          .eq('level_number', levelNumber)
          .order('question_number', ascending: true);

      if (response.isEmpty) {
        print('⚠️ No questions found for level $levelNumber in Supabase');
        // Fallback to hardcoded data
        return levelQuestions[levelNumber] ?? [];
      }

      return (response as List)
          .map((item) => WordQuestion.fromJson(item))
          .toList();
    } catch (e) {
      print('❌ Error loading questions from Supabase: $e');
      // Fallback to hardcoded data
      return levelQuestions[levelNumber] ?? [];
    }
  }

  // Get all levels (1-10)
  static Future<List<int>> getAllLevels() async {
    return List.generate(10, (index) => index + 1);
  }
}
